# Generated by Django 4.2.4 on 2023-09-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post_like_follow_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default=None),
        ),
    ]
